apiVersion: skaffold/v4beta3
kind: Config
manifests:
    rawYaml:
        - ./_infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: frission/auth
          context: auth
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.(ts|tsx|js|jsx)"
                    dest: .
