apiVersion: skaffold/v4beta3
kind: Config
manifests:
    rawYaml:
        - ./_infra/k8s/*
        - ./_infra/k8s-dev/*
build:
    local:
        push: false
    artifacts:
        - image: frission/auth
          context: auth
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "**/*.(ts|js)"
                    dest: .
        - image: frission/tickets
          context: tickets
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "**/*.(ts|js)"
                    dest: .
        - image: frission/orders
          context: orders
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "**/*.(ts|js)"
                    dest: .
        - image: frission/client
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "**/*.(ts|tsx|js|jsx)"
                    dest: .
        - image: frission/expiration
          context: expiration
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "**/*.(ts|js)"
                    dest: .
        - image: frission/payments
          context: payments
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "**/*.(ts|js)"
                    dest: .
