apiVersion: apps/v1
kind: Deployment
metadata:
    name: expiration-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: expiration
    template:
        metadata:
            labels:
                app: expiration
        spec:
            containers:
                - name: expiration
                  image: frission/expiration:latest
                  env:
                      - name: NATS_URL
                        value: "nats://nats-srv:4222"
                      - name: REDIS_HOST
                        value: expiration-redis-srv
                  resources:
                      requests:
                          memory: "350Mi"
                          cpu: "400m" # m stands for millicores (0.4 CPU)
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
