name: deploy-manifests

on:
    push:
        branches:
            - master
        paths:
            - "_infra/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}

            - name: Set up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v2

            - name: Get GKE credentials
              run: |
                  gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
                    --zone ${{ secrets.GKE_ZONE }} \
                    --project ${{ secrets.GCP_PROJECT_ID }}

            - name: Apply K8S Configurations
              run: |
                  kubectl apply -f ./_infra/k8s/*
                  kubectl apply -f ./_infra/k8s-prod/*
