name: deploy-auth

on:
    push:
        branches:
            - main
        paths:
            - "auth/**"
    workflow_dispatch: 

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd auth && docker build -t frission/auth .
            - run: docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
            - run: docker push frission/auth

            # Step 2: Authenticate to Google Cloud
            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}

            # Step 3: Set up gcloud CLI
            - name: Set up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v2

            # Step 4: Get GKE cluster credentials
            - name: Get GKE credentials
              run: |
                  gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
                    --zone ${{ secrets.GKE_ZONE }} \
                    --project ${{ secrets.GCP_PROJECT_ID }}

            # Step 6: Deploy to GKE
            - name: Deploy to GKE
              run: kubectl set image deployment/auth-depl auth=frission/auth

            - name: Restart Deployment
              run: kubectl rollout restart deployment/auth-depl
